modLoader="javafml"
loaderVersion="[32,)"
#updateJSONURL=""
issueTrackerURL="https://github.com/AppliedEnergistics/Applied-Energistics-2/issues"
displayURL="https://github.com/AppliedEnergistics/Applied-Energistics-2"
logoFile="logo.png"
#credits="Thanks for this example mod goes to Java"
authors="TeamAppliedEnergistics"
license="See GitHub repository for details"

[[mods]]
modId="appliedenergistics2"
version="${file.jarVersion}"
displayName="Applied Energistics 2"
description="A Mod about Matter, Energy and using them to conquer the world.."

[[dependencies.appliedenergistics2]]
    modId="forge"
    mandatory=true
    versionRange="[33.0.22,35.0.0)"
    ordering="NONE"
    side="BOTH"

[[dependencies.appliedenergistics2]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,1.17.0)"
    ordering="NONE"
    side="BOTH"
