name: 'Update translations'

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: git fetch origin --tags
        shell: bash
      - uses: ./.github/actions/gradle-setup
      - uses: actions/setup-node@v2
        with:
          node-version: "21"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Download new translations from crowdin
        run: ./gradlew downloadFromCrowdin --no-daemon --info
        env:
          GIT_BRANCH: master
          CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
      - name: Apply Formatting
        run: ./gradlew spotlessJsonApply --no-daemon --info
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.12.0
        with:
          commit-message: Updated Translations from Crowdin
          delete-branch: true
          title: Updated Crowdin Translations
          body: Updated Translations from Crowdin https://appliedenergistics2.crowdin.com/
